### ISSUE TITLE
Grey page - no loading due to errors

### ISSUE THREAD

**Issue by gabriel3l** [Flam3rboy/discord-bot-client#10]
Hi,

As per the title, this happens both on the [demo page](https://discordclient.com/) and using the local files.

Console is showing several 500 errors from "vacdn" while trying to get some JS assets.

**Comment by Flam3rboy** [comment]
yes, I'm aware of the issue and will fix it ASAP

**Comment by Flam3rboy** [comment]
I fixed it now, please try it again. 
If it doesn't work please reopen the issue.

**Comment by gabriel3l** [comment]
Asking to reopen the issue for the same purpose, @Flam3rboy
