### ISSUE TITLE
All servers are unavailable Due to outages it says when they are fine

### ISSUE THREAD

**Issue by cojored** [Flam3rboy/discord-bot-client#101]

**Comment by haydenwalker980** [comment]
I've gotten this issue too. Maybe include a description though?

**Comment by 930r** [comment]
I have the same problem i am using version 3.1.0 windows portable, the bot works fine other than not being able to use the bot client
I tried logging into my other bot and it actually worked fine on that one, so it's something that doesn't affect all bots, the bot that works is a much smaller one i only use for testing so maybe rate limiting has something to do with it?
![Discord_Bot_Client_QFzVdXDTgE](https://user-images.githubusercontent.com/59374337/104766977-18461100-5774-11eb-9cc6-fae7ee792ed8.png)

**Comment by Flam3rboy** [comment]
please state if the issue still persists tomorrow, because it could be that discord is having an outage and can't load at least one server

**Comment by 930r** [comment]
Last night after i sent that it got fixed on its own but as im writing this it is broken again

**Comment by Atharv-Agarwal** [comment]
+1 Same issue

**Comment by ard50500** [comment]
sameee

**Comment by isaackogan** [comment]
same here.
