### ISSUE TITLE
Member list's order is not respected

### ISSUE THREAD

**Issue by minhducsun2002** [Flam3rboy/discord-bot-client#103]
Bot client : 
![image](https://user-images.githubusercontent.com/32769878/91945295-0fa2f000-ed29-11ea-8ab5-49a7e9fc816b.png)
![image](https://user-images.githubusercontent.com/32769878/91945672-29dcce00-ed29-11ea-940b-9adb576f88ae.png)

Normal client :
![image](https://user-images.githubusercontent.com/32769878/91945533-1fbacf80-ed29-11ea-89b2-1ef1bc3a9981.png)

Same server, same channel.
It is also worth noting that in the bot client not everyone stays at the correct role (i.e. somebody is categorized to a role they don't have)

**Comment by Assfugil** [comment]
#8
