### ISSUE TITLE
2FA problem

### ISSUE THREAD

**Issue by Cliv69** [Flam3rboy/discord-bot-client#110]
When a server the bot is in has 2FA it says u need 2FA to make mod actions but when you try it says bots cant do this endpoint

**Comment by haydenwalker980** [comment]
You need to have 2FA instead.

**Comment by Nermal242** [comment]
> You need to have 2FA instead.

Do I need to enable 2FA for the Bot account or the owner account of the bot?

**Comment by Flam3rboy** [comment]
on the owner account of the bot
