### ISSUE TITLE
I can't open the application on mac

### ISSUE THREAD

**Issue by Daniellop1** [Flam3rboy/discord-bot-client#118]
It closes unexpectedly, I attach a screenshot:

<img width="996" alt="Screenshot 2020-09-09 at 19 59 31" src="https://user-images.githubusercontent.com/44546966/92636011-fc6ac400-f2d6-11ea-97a4-288c17b31511.png">

**Comment by Assfugil** [comment]
launch the executable from a terminal.

**Comment by Daniellop1** [comment]
> launch the executable from a terminal.

Still not working

**Comment by xMvdl-ui** [comment]
It doesn't work.

**Comment by makemake5050** [comment]
same issue

**Comment by TheNebulaCreeper** [comment]
has anyone found a way to fix this yet?

**Comment by klemmons72** [comment]
no fix yet

**Comment by xNaCly** [comment]
![image](https://user-images.githubusercontent.com/47723417/93234514-ab4a4c80-f77c-11ea-97d7-c98a269d405b.png)

**Comment by Daniellop1** [comment]
The application still does not work, please do not close the issue if it has not been solved

**Comment by TheNebulaCreeper** [comment]
I have found a fix to this. If you used the .dmg version, then open Terminal and run this command:
/Applications/Discord\ Bot\ Client.app/Contents/MacOS/Discord\ Bot\ Client
If it's in a different folder and not Applications, then replace Applications with the folder it's in. I.E. /Desktop/Discord\ Bot\ Client.app/Contents/MacOS/Discord\ Bot\ Client
Simple fix, but it worked for me.

**Comment by TheNebulaCreeper** [comment]
It might also work for the .zip version, but I'm not too sure as I've only used the .dmg version.

**Comment by kezvon** [comment]
> I have found a fix to this. If you used the .dmg version, then open Terminal and run this command:
> /Applications/Discord\ Bot\ Client.app/Contents/MacOS/Discord\ Bot\ Client
> If it's in a different folder and not Applications, then replace Applications with the folder it's in. I.E. /Desktop/Discord\ Bot\ Client.app/Contents/MacOS/Discord\ Bot\ Client
> Simple fix, but it worked for me.

It was working perfectly fine until this happened. When I open the app it's just a white window (for mac).
![image](https://user-images.githubusercontent.com/70430734/93320595-9a6d0a00-f854-11ea-80ef-9f7919b33738.png)

**Comment by Flam3rboy** [comment]
try pressing, Ctrl + R or click on View -> Reload

**Comment by kezvon** [comment]
> try pressing, Ctrl + R or click on View -> Reload

Still doesn't work, proof:
https://www.youtube.com/watch?v=VXiRj2CLkSE

**Comment by Flam3rboy** [comment]
@kezvon you copied the wrong thing, your client secret is not your bot token. Make sure to copy this:
![image](https://user-images.githubusercontent.com/34555296/93355731-acdc4900-f83e-11ea-8e96-5c79f9da3134.png)

**Comment by kezvon** [comment]
> @kezvon you copied the wrong thing, your client secret is not your bot token. Make sure to copy this:
> ![image](https://user-images.githubusercontent.com/34555296/93355731-acdc4900-f83e-11ea-8e96-5c79f9da3134.png)

Oh shii, forgot about that!! Need more sleep LMAOO! Thank you man, you're very helpful to the Discord Community!
