### ISSUE TITLE
Some feedbacks

### ISSUE THREAD

**Issue by Assfugil** [Flam3rboy/discord-bot-client#12]
First thank you for making such a great client!
## Bugs
- Member list won't load or load very slowly, event with GUILD_MEMBERS intents enabled
- Scrambled member list as mentioned in #8 
- Client user has all flags
- Cannot connect to voice channel
- The bot "stays" in voice channel even if you leave it
- If you log out or provide an invalid token,you are redirected to the email + password login screen
## Suggestions
- Add bulk delete support
- Add DM by user ID

**Comment by Flam3rboy** [comment]
Thanks for taking time to make an issue.
I know of alle the bugs, and working on a fix.
Also the suggestions are pretty easy, so I should be able to implement them.

**Comment by byte1080** [comment]
> Client user has all flags
You can disable that if you want by modifying index.html and src/loader.js, just change the t.user.flags to whatever user flag you want

**Comment by MirayXS** [comment]
> Thanks for taking time to make an issue.
> I know of alle the bugs, and working on a fix.
> Also the suggestions are pretty easy, so I should be able to implement them.

hey. This could be strange, but if you gonna fix the " all flag (badges) on bot " issue, please make an option to disable enable this!! i really like.

**Comment by MirayXS** [comment]
> Client user has all flags:
> You can disable that if you want by modifying index.html and src/loader.js, just change the t.user.flags to whatever user flag you want

there's no loader.js
