### ISSUE TITLE
Doesnt let me login as a bot

### ISSUE THREAD

**Issue by Rayyan2650** [Flam3rboy/discord-bot-client#124]
So basically I download the installer and once I opened it said to give the token like usually so I did then I waited for it to load then it said to give login and password but I never saw this so anyways I gave it so then it logged me in to my own account instead of logging me in As a bot i try to login 4x but the same thing happened please solve this!!!!!!!!!!!!

**Comment by Flam3rboy** [comment]
you entered the wrong bot token,

**Comment by Rayyan2650** [comment]
i did and it didnt work..

**Comment by Rayyan2650** [comment]
i did everything piece by piece and it still didn't work once I click on login and and enter my token after some seconds it will show me to enter a email address and password! and if I do this I get my own account logged in and not the bot account !  please help me  and your method still didn't work
