### ISSUE TITLE
Doesnt Let Me Login In As A Bot Still

### ISSUE THREAD

**Issue by Rayyan2650** [Flam3rboy/discord-bot-client#125]
it still won't let me Login as a bot I putted the *Correct token and still it didn't work it gave me the same problem* Once I entered the Token I pressed Login and After seconds it then asked me for my email address and password and if I put it in it will log me into my account and *Will not log me in as a bot*.

**Comment by Assfugil** [comment]
Does the "token" have 3 `.`s in it?

**Comment by Rayyan2650** [comment]
let me check

**Comment by Rayyan2650** [comment]
doesnt have anything included with that.

**Comment by Flam3rboy** [comment]
then its not your bot token, make sure you copied this:
![image](https://user-images.githubusercontent.com/34555296/93334975-0c7a2a80-f826-11ea-9c52-6e0953c08eff.png)
