### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by kezvon** [Flam3rboy/discord-bot-client#126]
For all the Mac users, there is a way to get into the Bot Client. Open Terminal and paste **"/Applications/Discord\ Bot\ Client.app/Contents/MacOS/Discord\ Bot\ Client"** in it, then press enter. Make sure you drag the bot into the Applications folder or replace "Applications" with the "Desktop" if it's on the desktop.

Problem:
When did the terminal trick and opened it, it won't show anything but a white screen? It works, you paste the log-in token in and, it works. But, it will take me to the normal log-in screen. How would I fix it?

https://cdn.discordapp.com/attachments/739496106945413200/755735475687391242/Screen_Shot_2020-09-16_at_7.39.37_pm.png
https://cdn.discordapp.com/attachments/739496106945413200/755735492280188948/Screen_Shot_2020-09-16_at_8.20.07_pm.png

Screen Recording / Proof
https://www.youtube.com/watch?v=If2TCuA7YBE

**Comment by Flam3rboy** [comment]
Your client secret is not your bot token, make sure to copy this:
![image](https://user-images.githubusercontent.com/34555296/93335241-6c70d100-f826-11ea-8afb-e28e15d5f16a.png)
