### ISSUE TITLE
logging out and back in as bot

### ISSUE THREAD

**Issue by AreSeven73** [Flam3rboy/discord-bot-client#128]
when I logged in as a bot, I had no problems, however I had somehow managed to log myself out, However when tried to log back in, it would ask for the client id but then redirect me to the normal user login page

I tried uninstalling and reinstalling however the problem persisted

I even deleted the bot and remade it however nothing changed

I may be being stupid but this may be a problem others may face

**Comment by Justjdupuis** [comment]
Click on force reset I think it's in file or something at the top of the window

**Comment by Yare626** [comment]
Same I can’t login using Penguin App On my Crome

**Comment by AreSeven73** [comment]
> Click on force reset I think it's in file or something at the top of the window

already tried that - doesn't really change anything

**Comment by xamionex** [comment]
same thing happened to me, accidentally put in wrong token then it sent me to normal user login and then i just closed it and opened again. Then it asked me for token again
