### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by qamyz** [Flam3rboy/discord-bot-client#13]
I'm sorry for the vague title, though for some reason it's not working. I tried both through your website + the source code one. I go to the localhost and just has a blank gray screen, if you could help that'd be appreciated.

**Comment by mihabozic123** [comment]
same for me
looks ike discordfags updated some stuffs

**Comment by qamyz** [comment]
> same for me
> looks ike discordfags updated some stuffs

I guess so, I thought it was only me.

**Comment by Flam3rboy** [comment]
I can confirm it, and fixed it now.
