### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by DAVIREPYT8** [Flam3rboy/discord-bot-client#131]
Hi im an user who downloaded this Client in a Windows 7 but a white screen invades my space... 

I opened the program and put me in left corner upside "File / Edit / View / Window / Help" i thinked thats normal but i have a Black screen and in 5 seconds appear the white screen, i pressed Ctrl + R but dosen't work

Please help me

**Comment by Toyotacamry2001** [comment]
I had accidently deleted discord and the bot client and upon re-installing it gets stuck halfway when installing.

**Comment by Flam3rboy** [comment]
use windows 10
