### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Toyotacamry2001** [Flam3rboy/discord-bot-client#132]
I had accidently unistalled the bot client and upon re-installing it the progress bar gets stuck around halfway. I have unistalled all of its previous data from my pc and used %appdata% and %localappdata% to get rid of any traces so it has a clean install but it didn't work. Any ideas on how to fix this

**Comment by ThePilotNinja** [comment]
yes re download it

**Comment by Toyotacamry2001** [comment]
> yes re download it

thats the problem it doesn't redownload and I have tried several times deleting and trying to download but the progress bar doesn't get past halfway

**Comment by Smokva69** [comment]
yea i have this problem too

**Comment by JustinPooters** [comment]
I'll edit this client to be working perfectly again, check my discord in a few weeks (1 or 2 weeks)

**Comment by ThePilotNinja** [comment]
Ok

**Comment by zachariapopcorn** [comment]
Just use the portable one

**Comment by xNaCly** [comment]
> I'll edit this client to be working perfectly again, check my discord in a few weeks (1 or 2 weeks)

🤡
