### ISSUE TITLE
Installing npm dependencies fails

### ISSUE THREAD

**Issue by Tymanyay** [Flam3rboy/discord-bot-client#134]
```
npm ERR! Unexpected end of JSON input while parsing near '...wIR6jgcsdJ1nW2f\nYV9m'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\beckm\AppData\Roaming\npm-cache\_logs\2020-09-27T16_44_23_048Z-debug.log
```

when running `npm i`

**Comment by Strajeti** [comment]
This is an Python project so you have to use `pip` instead of [npm](url). Full commad is `pip install requests fake_useragent tqdm` be sure that you are executing it inside the project file and you can see Nitrx.py when you run `dir` (or `ls` for Linux).
