### ISSUE TITLE
i cant place token

### ISSUE THREAD

**Issue by ThePilotNinja** [Flam3rboy/discord-bot-client#135]
Hello, i tried pasting my token, its not letting me paste, i dont know if the issue is from me or from the discord bot client.

**Comment by phillol1234** [comment]
stop spamming and:
<code> it is your issue, do not repeat this 100 times, you must refresh for it to work </code>
<b> Do not make any other issues. </b>

**Comment by ThePilotNinja** [comment]
bruh im not spamming. alphii wtf

**Comment by MuhannadYT** [comment]
do ctrl+shift+r
