### ISSUE TITLE
Just blank.

### ISSUE THREAD

**Issue by Reat2** [Flam3rboy/discord-bot-client#14]
![image](https://user-images.githubusercontent.com/44247732/89110986-9ad55100-d41e-11ea-9cc8-c885faed2596.png)
and now this happened
![image](https://user-images.githubusercontent.com/44247732/89111055-55fdea00-d41f-11ea-958d-86b55a0c5bf0.png)

**Comment by Flam3rboy** [comment]
Yes I'm working on a fix.
Discord changed many things and now the browser can't just download the source code anymore.
I've managed to do a first fix with a [browser extension](https://github.com/Flam3rboy/discord-bot-client/blob/master/extension.zip?raw=true).
If you know how to install a .zip extension go ahead, else wait for the chrome/firefox extension store to approve it.

**Comment by buachigithub** [comment]
good!! ty <3

**Comment by DeltaCoderr** [comment]
@Flam3rboy  I have downloaded the extension, Now what should I do?.

**Comment by Flam3rboy** [comment]
@DeltaCoderr If you know how to install a .zip extension go ahead, else wait for the chrome/firefox extension store to approve it.

**Comment by DeltaCoderr** [comment]
aight 👍

**Comment by Depilitis** [comment]
I installed the extension, and went to localhost:3000. It shows the same thing! Please help.

**Comment by bigbenster702** [comment]
> I installed the extension, and went to localhost:3000. It shows the same thing! Please help.

Go to http://botclient.tk/

**Comment by Depilitis** [comment]
> > I installed the extension, and went to localhost:3000. It shows the same thing! Please help.
> 
> Go to http://botclient.tk/

When I do, it tells me I need the extension.

I am on Opera GX.

**Comment by bigbenster702** [comment]
> > > I installed the extension, and went to localhost:3000. It shows the same thing! Please help.
> > 
> > 
> > Go to http://botclient.tk/
> 
> When I do, it tells me I need the extension.
> 
> I am on Opera GX.
> 
> I also tried this on FIrefox.
> ![image](https://user-images.githubusercontent.com/69131802/89142988-f0345f80-d4fd-11ea-9be0-d3a00331c96c.png)
> 
> ![image](https://user-images.githubusercontent.com/69131802/89143009-fcb8b800-d4fd-11ea-9300-ef9522b767e0.png)
> ![image](https://user-images.githubusercontent.com/69131802/89143067-24a81b80-d4fe-11ea-8769-071f34eb256b.png)

Download chrome and then do it on that and it should work

**Comment by Depilitis** [comment]
> > > > I installed the extension, and went to localhost:3000. It shows the same thing! Please help.
> > > 
> > > 
> > > Go to http://botclient.tk/
> > 
> > 
> > When I do, it tells me I need the extension.
> > I am on Opera GX.
> > I also tried this on FIrefox.
> > ![image](https://user-images.githubusercontent.com/69131802/89142988-f0345f80-d4fd-11ea-9be0-d3a00331c96c.png)
> > ![image](https://user-images.githubusercontent.com/69131802/89143009-fcb8b800-d4fd-11ea-9300-ef9522b767e0.png)
> > ![image](https://user-images.githubusercontent.com/69131802/89143067-24a81b80-d4fe-11ea-8769-071f34eb256b.png)
> 
> Download chrome and then do it on that and it should work

I'll update you if it works/doesn't work.

**Comment by bigbenster702** [comment]
> > > > > I installed the extension, and went to localhost:3000. It shows the same thing! Please help.
> > > > 
> > > > 
> > > > Go to http://botclient.tk/
> > > 
> > > 
> > > When I do, it tells me I need the extension.
> > > I am on Opera GX.
> > > I also tried this on FIrefox.
> > > ![image](https://user-images.githubusercontent.com/69131802/89142988-f0345f80-d4fd-11ea-9be0-d3a00331c96c.png)
> > > ![image](https://user-images.githubusercontent.com/69131802/89143009-fcb8b800-d4fd-11ea-9300-ef9522b767e0.png)
> > > ![image](https://user-images.githubusercontent.com/69131802/89143067-24a81b80-d4fe-11ea-8769-071f34eb256b.png)
> > 
> > 
> > Download chrome and then do it on that and it should work
> 
> I'll update you if it works/doesn't work.

K

**Comment by Depilitis** [comment]
> > > > > > I installed the extension, and went to localhost:3000. It shows the same thing! Please help.
> > > > > 
> > > > > 
> > > > > Go to http://botclient.tk/
> > > > 
> > > > 
> > > > When I do, it tells me I need the extension.
> > > > I am on Opera GX.
> > > > I also tried this on FIrefox.
> > > > ![image](https://user-images.githubusercontent.com/69131802/89142988-f0345f80-d4fd-11ea-9be0-d3a00331c96c.png)
> > > > ![image](https://user-images.githubusercontent.com/69131802/89143009-fcb8b800-d4fd-11ea-9300-ef9522b767e0.png)
> > > > ![image](https://user-images.githubusercontent.com/69131802/89143067-24a81b80-d4fe-11ea-8769-071f34eb256b.png)
> > > 
> > > 
> > > Download chrome and then do it on that and it should work
> > 
> > 
> > I'll update you if it works/doesn't work.
> 
> K

This is random, but mind adding me on DIscord? You seem chill, and it'd be easier. Q_Q#8334

**Comment by Depilitis** [comment]
![image](https://user-images.githubusercontent.com/69131802/89143489-a0ef2e80-d4ff-11ea-8db0-c6b002677ac8.png)


Still didn't work.

**Comment by bigbenster702** [comment]
> ![image](https://user-images.githubusercontent.com/69131802/89143489-a0ef2e80-d4ff-11ea-8db0-c6b002677ac8.png)
> 
> Still didn't work.

Did you install the extension on to chrome?

**Comment by Depilitis** [comment]
No, what's it called??

**Comment by bigbenster702** [comment]
> No, what's it called??

You have to download the extension by going to the 2nd post and clicking on the blue letters that say “Browser extension”

**Comment by Depilitis** [comment]
> > No, what's it called??
> 
> You have to download the extension by going to the 2nd post and clicking on the blue letters that say “Browser extension”

What do you mean by second post?

**Comment by Depilitis** [comment]
> > > No, what's it called??
> > 
> > 
> > You have to download the extension by going to the 2nd post and clicking on the blue letters that say “Browser extension”
> 
> What do you mean by second post?

Nevermind, that's what I did. I installed that and went to localhost:3000. All it does is take a bit and then says it crashed. I installed Dependencies, and did npm install.

**Comment by bigbenster702** [comment]
> > > No, what's it called??
> > 
> > 
> > You have to download the extension by going to the 2nd post and clicking on the blue letters that say “Browser extension”
> 
> What do you mean by second post?

This 
![90CF4EA4-B376-4DE6-B725-429EFBCB9D00](https://user-images.githubusercontent.com/48159706/89143899-c71dca00-d511-11ea-8fa0-af87014be64c.jpeg)

**Comment by Depilitis** [comment]
Would you mind telling me how to install a browser extension?

**Comment by bigbenster702** [comment]
Well download the zip and extract it first

**Comment by Depilitis** [comment]
Done.

**Comment by Depilitis** [comment]
Please add me on Discord so this is easier. Q_Q#8334

**Comment by bigbenster702** [comment]
Then go to the Extensions page and turn on developer mode at the top right

**Comment by Depilitis** [comment]
CTRL + i?

**Comment by bigbenster702** [comment]
To get there click the Chrome menu icon and select Extensions from the Tools menu.

**Comment by bigbenster702** [comment]
> Then go to the Extensions page and turn on developer mode at the top right

Then do this

**Comment by bigbenster702** [comment]
Once it is on tell me

**Comment by Depilitis** [comment]
I went to Google Extensions website. I clicked the gear, then developer dashboard. This is confusing, I am sorry for not understanding.

**Comment by bigbenster702** [comment]
Ohhhh that is what is wrong, ok so click the 3 lines at the top right then find the button that says Extensions and click that

**Comment by Depilitis** [comment]
Where are the three lines? The 9 dots?

**Comment by bigbenster702** [comment]
Yah the dots

**Comment by Depilitis** [comment]
Okay, done.

**Comment by bigbenster702** [comment]
Do you see a button that says developer mode at the top right now?

**Comment by Depilitis** [comment]
I'm in the chrome web store.

**Comment by Depilitis** [comment]
![image](https://user-images.githubusercontent.com/69131802/89144344-4acfba80-d502-11ea-8687-85dbfec38ba8.png)

**Comment by bigbenster702** [comment]
Uhhh

**Comment by bigbenster702** [comment]
Ok hold on, I have a idea

**Comment by Depilitis** [comment]
Okay.

**Comment by bigbenster702** [comment]
I need to get on my computer hold on

**Comment by Depilitis** [comment]
Okay.

**Comment by bigbenster702** [comment]
Go to chrome://extensions

**Comment by Depilitis** [comment]
Okay.

**Comment by Depilitis** [comment]
Done.

**Comment by Depilitis** [comment]
Dev mode on.

**Comment by bigbenster702** [comment]
K now on the left click unpacked and then find that folder that it is in and click open

**Comment by Depilitis** [comment]
It says manifest is missing.

**Comment by bigbenster702** [comment]
Uh

**Comment by Depilitis** [comment]
Oh my god, I forgot to extract it to my folder, sorry haha.

**Comment by Depilitis** [comment]
Thank you so much! Time to test it!

**Comment by Depilitis** [comment]
Thank you so much. It works, I'm gonna log in.

**Comment by bigbenster702** [comment]
Your’re welcome make sure to go to http://botclient.tk/ for it to work

**Comment by Depilitis** [comment]
YES! IT WORKS! THANK YOU SO MUCH!

**Comment by bigbenster702** [comment]
You’re very welcome! I am here to help!

**Comment by DeltaCoderr** [comment]
Damn, we really did start a big convo right there 👀

**Comment by veryasiandev** [comment]
@bigbenster702 hey, I want to run this locally so I downloaded the code(also extracted) and Node so then what do I do next ?
I ran the node and it said server listening on 3000 but when I go to localhost 3000 its just blank.  
![lskfslkdfsdfsfsdfsdfsfsfd](https://user-images.githubusercontent.com/69243139/89403940-0c5c1a80-d711-11ea-9ea0-af9ae581776a.png)
