### ISSUE TITLE
I put in my token and then it tells me to log into a human account

### ISSUE THREAD

**Issue by JII060** [Flam3rboy/discord-bot-client#142]
![image](https://user-images.githubusercontent.com/72321787/95002194-39ba2d00-05c9-11eb-842d-623a2b475d4d.png)

**Comment by CTRL-ALT-EXIST** [comment]
@JII060 You need to relaunch the app to get the login w/token screen

**Comment by Flam3rboy** [comment]
you copied the client secret, but you need the bot token
