### ISSUE TITLE
Bot Login

### ISSUE THREAD

**Issue by Lormran** [Flam3rboy/discord-bot-client#148]
Hello! I was trying to login to the bot account with my token, but then it took me to the regular login screen. Is this supposed to happen? Thank you
![image_2020-10-08_092203](https://user-images.githubusercontent.com/72559812/95464268-b9d4ef80-0947-11eb-9d36-3ac85edfe018.png)
![image_2020-10-08_092311](https://user-images.githubusercontent.com/72559812/95464388-e25ce980-0947-11eb-8128-35bbf6c8a582.png)

**Comment by Muhannad0AlAbrash** [comment]
the same error did u find a fix for it

**Comment by Muhannad0AlAbrash** [comment]
I tried it with the portable ver, and it worked

**Comment by MuhannadYT** [comment]
after I logged out I was unable to login, same error as before

**Comment by MuhannadYT** [comment]
go to build a bot and get the token from there

**Comment by Flam3rboy** [comment]
you probably copied the client secret, but you need to copy the bot token
