### ISSUE TITLE
My Mac Says This is from an Unidentified Developer

### ISSUE THREAD

**Issue by pacse** [Flam3rboy/discord-bot-client#151]
My error code:
"“Discord Bot Client” can’t be opened because it is from an unidentified developer.
Your security preferences allow installation of only
apps from the App Store and identified developers.

Chrome downloaded this file on October 8, 2020 from
 github.com."
does this contain malware?

**Comment by Flam3rboy** [comment]
of course not, you can even build it yourself.
I just don't pay 100€ a year for the mac developer license

**Comment by pacse** [comment]
please provide more proof that this doesn't contain malware

**Comment by Flam3rboy** [comment]
you can see the source code its all open source, you can even build it yourself. Other Developer's are invited to have a look and evaluate that this software doesn't contain malware.

**Comment by DarrenAlex** [comment]
of course this isnt. it's open source. macs are just shitty tbh when it comes to stuff like these

**Comment by pacse** [comment]
please remove swearing @DarrenAlex

**Comment by pacse** [comment]
@DarrenAlex

**Comment by Flam3rboy** [comment]
please do not spam @pacse

**Comment by pacse** [comment]
> please do not spam @pacse

OK sorry
