### ISSUE TITLE
localhost:3000 black screen

### ISSUE THREAD

**Issue by Smile-Apple-0** [Flam3rboy/discord-bot-client#154]
I opened Server Port 3000 and npm install, npm run 
I connected to localhost:3000 but black screen shows
![image](https://user-images.githubusercontent.com/65323308/95993480-22512e80-0e6a-11eb-92bc-be78eef3db47.png)

**Comment by Flam3rboy** [comment]
you can only use the app

**Comment by DwifteJB** [comment]
what app?
