### ISSUE TITLE
Cant login with token

### ISSUE THREAD

**Issue by CyberFlo2005** [Flam3rboy/discord-bot-client#158]
if I try to login with my bot token, I just get redirected to the default login side from discord. I already tried ctrl +shift +r multiple times. I also tried the portable and the installer (running on windows)
![image](https://user-images.githubusercontent.com/63535940/96334556-028c5700-1072-11eb-8eb1-3e97ee224e91.png)

**Comment by Flam3rboy** [comment]
Your token is invalid, you probably copied the client secret, however you need to bot token

**Comment by Flam3rboy** [comment]
I'll keep open the issue for others, who have the same problem

**Comment by CyberFlo2005** [comment]
I actually copied the token of my bot. First I added it to my server as Administrator with the OAuth2 URL generator with the bot scope. then I went to bot (which I already added) and copied my token. however, if try to login with it the error occurs.

btw. now im getting this screen if I try to start it (also tried ctrl + shift + r)
![image](https://user-images.githubusercontent.com/63535940/96348520-c379f800-10a9-11eb-9cb9-056d01ee2f4a.png)

**Comment by Flam3rboy** [comment]
some firewall is blocking the connection, also note that only windows 10 is supported

**Comment by CyberFlo2005** [comment]
im running windows 10, however I got it working. I just reinstalled the programm

**Comment by ColibFox** [comment]
yeah i cant log in too

**Comment by Ramsy2** [comment]
Hey I also need some help. I've the same problem as some others here. I'm using Windows 10 and when i try to log in with the token, it takes me to the usual login page.

**Comment by Flam3rboy** [comment]
> Your token is invalid, you probably copied the client secret, however you need the bot token

**Comment by TechproTaz** [comment]
> 
> 
> some firewall is blocking the connection, also note that only windows 10 is supported

I tested it and it works on windows 7 too
