### ISSUE TITLE
Can't see server members

### ISSUE THREAD

**Issue by Dellafj911** [Flam3rboy/discord-bot-client#168]

**Comment by keatonbuilder** [comment]
This is just the Discord Bot API as bots see server members differently than a normal user.

**Comment by grifgrif** [comment]
You need to check this to request User List
![mRP 1](https://user-images.githubusercontent.com/47899313/98467556-476d5e80-21d6-11eb-8306-5c2e469ca68e.png)

**Comment by Flam3rboy** [comment]
also its a bit buggy, don't expect it to load the member list

**Comment by BuilderHD** [comment]
We trying to fix this.

**Comment by joebyjo** [comment]
Its not the Server Member Intent,My bot has the permission and still cant see

**Comment by RBXCommunity** [comment]
We Cant See The Members List Cant U Just Make An Copy Of The Discord App?

**Comment by Flam3rboy** [comment]
I'm in fact doing this: https://github.com/discord-open-source

**Comment by Flam3rboy** [comment]
duplicate of #144
