### ISSUE TITLE
Firefox estension support

### ISSUE THREAD

**Issue by ivanghi1995** [Flam3rboy/discord-bot-client#17]
I'm a firefox user and i can only use the new extension on chrome, that's all.

**Comment by ivanghi1995** [comment]
After 5 tries the extension magically worked

**Comment by Flam3rboy** [comment]
ok thats weird, I tested it on Firefox Mac and it worked.
For any other user here, wait a few days until the official firefox extension is approved.

**Comment by ivanghi1995** [comment]
> ok thats weird, I tested it on Firefox Mac and it worked.
> For any other user here, wait a few days until the official firefox extension is approved.

Sooo basically the extension dissapeared and it gives me error again, guess I'll wait

**Comment by Flam3rboy** [comment]
just use the application
