### ISSUE TITLE
Can't mute people

### ISSUE THREAD

**Issue by luxness** [Flam3rboy/discord-bot-client#170]
I cannot mute people

**Comment by BLAISE19556** [comment]
I had the same problem but I can help make a role called muted and at the bottom make it so they can't speak or send messages

**Comment by xNaCly** [comment]
# Can't mute people [#170](https://github.com/Flam3rboy/discord-bot-client/issues/170)
![image](https://better-issues.herokuapp.com/render_issue?issue=https://github.com/Flam3rboy/discord-bot-client/issues/170&type=compact)

Personaly i cant recreate this issue, try checking if the bot has the permissions for doing certain actions
![image](https://user-images.githubusercontent.com/47723417/98446769-20545580-2120-11eb-9c25-798809b03035.png)

**Comment by luxness** [comment]
i mean, i cannot mute people in my DMs not voice. because sometimes they spam my DMs. and i can mute servers but can't mute channels
