### ISSUE TITLE
Chromebook version?

### ISSUE THREAD

**Issue by PresentGamer** [Flam3rboy/discord-bot-client#179]
I saw someone say android version so I thought to myself this. Could it be available on chromebook in google play store?

**Comment by xNaCly** [comment]
linux version? google please

**Comment by LakerHayk** [comment]
Install the Linux Beta if you haven't already and install the client through the terminal

**Comment by AwxyyDeveloper** [comment]
Instead of relying on this on plain chromebook. Maybe try enabling ChromeOS's new Linux Beta mode. It lets you run linux programs.

**Comment by MCPE2019Github** [comment]
yes i am using it on my chromebook
so it works

**Comment by MEEBLOX** [comment]
Go to https://chrome.google.com/webstore/detail/discord-bot-client/dighjoofcdkhjloaeakagmfnbiehebbb?utm_source=chrome-app-launcher Download the extension and then go to http://Discordbotclient.jtmaveryk.repl.co
And HOW THE FUCK WOULD HE TRANSFER IT TO GPS (GOOGLE PLAY STORE) THATS IMPOSSIBLE GITHUB IS ONLY FOR CODERS/PROGRAMMERS DUHH. (I'm literally on chromebook) (I'm alergic to dumb)

**Comment by Flam3rboy** [comment]
The extension isn't supported anymore and you don't need it. You just need the program, however it isn't available for chromebooks.

**Comment by DodoGames7** [comment]
rip

**Comment by LightnerDev** [comment]
> The extension isn't supported anymore and you don't need it. You just need the program, however it isn't available for chromebooks.

Well can you explain how I am using it on my chromebook?

**Comment by Flam3rboy** [comment]
lol idk

**Comment by LightnerDev** [comment]
> lol idk
[here](https://github.com/Flam3rboy/discord-bot-client/discussions/225) is a way

**Comment by LightnerDev** [comment]
and Flam3rboy never responds

**Comment by Flam3rboy** [comment]
So it's possible, can I close the issue now?
