### ISSUE TITLE
Question: Please Forgive Me

### ISSUE THREAD

**Issue by CE1CECL** [Flam3rboy/discord-bot-client#18]
Why do things still look like the older version of discord, i'm looking at the changelog and its still mentioning about "Server Video being New" when it should be "A message from our founders, Jason & Stan". I dont get it
also what was "q2497732f.tk"? it has the old discord homepage when i went to it!
I'm Just asking!

**Comment by Flam3rboy** [comment]
q2497732f.tk was a temporary page because discord blocks them
its still the old version, because its much effort to update it
