### ISSUE TITLE
Broken, badly

### ISSUE THREAD

**Issue by KewlSage** [Flam3rboy/discord-bot-client#191]
I think the issue is v6 endpoints such as channels and regions not being usable by bots anymore, and thanks to that this client is now virtually useless.

**Comment by AwxyyDeveloper** [comment]
There's nothing to do now. The application's developer has discontinued this project and will not be any more further updates.

**Comment by BuilderHD** [comment]
> There's nothing to do now. The application's developer has discontinued this project and will not be any more further updates.

I resumed work updates will be then. we are trying to fix a couple of bugs and add one cool thing.

**Comment by BuilderHD** [comment]
> I think the issue is v6 endpoints such as channels and regions not being usable by bots anymore, and thanks to that this client is now virtually useless.

accepted ,we will fix it.
