### ISSUE TITLE
chrome extentions support

### ISSUE THREAD

**Issue by Ezrabro** [Flam3rboy/discord-bot-client#199]
Hi there
I'm using discord bot client portable and I guess it's like a chrome based browser
so I thought if there is a way to use extensions.
![image](https://user-images.githubusercontent.com/67427897/101591274-680d1c00-3a01-11eb-9b3e-c5cef17ef774.png)

like a VPN because I like to browse privately

 could you add it?

or if you can add a built-in VPN that only affect the discord bot client application

**Comment by Flam3rboy** [comment]
yes but I would still need to host it on a server with domain, and it got terminated before
