### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by nicho01022** [Flam3rboy/discord-bot-client#204]
How to Uninstall it

**Comment by Flam3rboy** [comment]
what operating system are you using?

**Comment by nicho01022** [comment]
Windows 10

**Comment by Flam3rboy** [comment]
You just uninstall the bot client like any other program:
https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98
