### ISSUE TITLE
Won't even run

### ISSUE THREAD

**Issue by haydenwalker980** [Flam3rboy/discord-bot-client#218]
I installed nodejs via apt. When I run it i get this error.

using npm start  
![image](https://user-images.githubusercontent.com/37120379/105941696-dbe7a000-6012-11eb-8e2b-6da29b038dd3.png)  
using node .  
![image](https://user-images.githubusercontent.com/37120379/105941815-1f420e80-6013-11eb-8638-1506b2eeedf1.png)  
using electron .  
![image](https://user-images.githubusercontent.com/37120379/105941900-44368180-6013-11eb-8b70-730a310929b9.png)  
Would be nice if I got help.

**Comment by Flam3rboy** [comment]
you forgot to install the dependencies:
```
npm i
```
