### ISSUE TITLE
Issues with packages in the README

### ISSUE THREAD

**Issue by Assfugil** [Flam3rboy/discord-bot-client#22]
First, FreeBSD is not Linux,
Also, the AppImage provided won't work on distros using musl libc (e.g. void linux and alpine linux)

Lastly, some build instructions would be nice! :heart:

**Comment by Flam3rboy** [comment]
Sorry, I don't have a linux OS to test but you can build it yourself: 
Install NodeJS: https://nodejs.org/en/download/
Clone the repository and install the dependencies:
```
git clone https://github.com/Flam3rboy/discord-bot-client
cd discord-bot-client
cd electron
npm i --dev
npm start
```
