### ISSUE TITLE
dosent load

### ISSUE THREAD

**Issue by HaMolX** [Flam3rboy/discord-bot-client#226]
it dont load

**Comment by Flam3rboy** [comment]
what os are you using?
If its just a white screen press Ctrl +R

**Comment by Aki26-GamePlay** [comment]
it's doesn't loading messages for me too. (OS: Win10 Enterprise)

**Comment by smikkelbakje** [comment]
![image](https://user-images.githubusercontent.com/59176120/107620008-52f87780-6c54-11eb-89f0-bfcdb07712a2.png)

yea its just empty

**Comment by Flam3rboy** [comment]
just restart the program and logout and login again

**Comment by nsde** [comment]
> just restart the program and logout and login again
I have the same problem. That does not work.
