### ISSUE TITLE
acting like a virus

### ISSUE THREAD

**Issue by soapy75** [Flam3rboy/discord-bot-client#228]
kept attempting to crash my driver i am not sure if it is a virus or not or maybe it is because im on an old pc

**Comment by Flam3rboy** [comment]
duplicate of #80 
note that only windows 10 is supported

**Comment by soapy75** [comment]
oh lol im on windows 7

**Comment by soapy75** [comment]
it kept attempting to crash my drive and then it would recover

**Comment by Flam3rboy** [comment]
yeah has probably nothing to do with the bot client, I just use plain Electron
but it doesn't work on windows 7 either, so you can't use it anyways
