### ISSUE TITLE
No servers error

### ISSUE THREAD

**Issue by dutchxarms** [Flam3rboy/discord-bot-client#233]
it worked fine before but some reason no servers show up and says  some malfunction https://prnt.sc/1006jh6
my bot is in 300 + servers? any ideas are welcome:) i always loved using this

**Comment by SpielenmitLili** [comment]
I've got the same problem like you with my bot. It is in 59 servers.

**Comment by dutchxarms** [comment]
> I've got the same problem like you with my bot. It is in 59 servers.

found out when having discord bot client open. and inviting it to a server u just made (so make one)
then it shows all servers after while not sure if it works everytime lol

**Comment by SpielenmitLili** [comment]
> > I've got the same problem like you with my bot. It is in 59 servers.
> 
> found out when having discord bot client open. and inviting it to a server u just made (so make one)
> then it shows all servers after while not sure if it works everytime lol

Okay, thanks for the help. @dutchxarms

**Comment by Flam3rboy** [comment]
duplicate of #241
