### ISSUE TITLE
Not working on mac 

### ISSUE THREAD

**Issue by Kangaroo379** [Flam3rboy/discord-bot-client#247]
I tried the fix from the other issue about this which was running the terminal app, but
 that did not work it just opened a terminal window with stuff I do not understand.
I linked images of my errors below
<img width="251" alt="Screenshot 2021-04-19 at 16 16 54" src="https://user-images.githubusercontent.com/69469132/115251450-dccc3180-a12a-11eb-98c5-1466c59b9dbd.png">
<img width="566" alt="Screenshot 2021-04-19 at 16 17 31" src="https://user-images.githubusercontent.com/69469132/115251494-e81f5d00-a12a-11eb-9ba8-aa31ba5b5873.png">

**Comment by Flam3rboy** [comment]
oh that doesn't seem right.
Never happened for me I'll have a look

**Comment by Kangaroo379** [comment]
To make it more clear I tried oppening it normally as seen by the image on top then tried the terminal way which resulted in the image below

**Comment by Kangaroo379** [comment]
> oh that doesn't seem right.
> Never happened for me I'll have a look
Thank you.

**Comment by Kangaroo379** [comment]
Any updates yet?

**Comment by Kangaroo379** [comment]
I think It works now using the terminal method. 
Thanks for your support
