### ISSUE TITLE
Dont see Private messages

### ISSUE THREAD

**Issue by gabrielmaster123** [Flam3rboy/discord-bot-client#248]
I dont get private messages but I know it is possilble for a bot to write private messages

**Comment by Flam3rboy** [comment]
on startup the dm channels can't be loaded, but if someones write the bot, while the bot client is open, it should show it

**Comment by GrayLanterns** [comment]
> on startup the dm channels can't be loaded, but if someones write the bot, while the bot client is open, it should show it

the bot can't send/receive friend requests, can it?

**Comment by Flam3rboy** [comment]
no #250
