### ISSUE TITLE
website down? and my website i hosted is blank

### ISSUE THREAD

**Issue by typicalninja493** [Flam3rboy/discord-bot-client#25]
when I go to https://botclient.tk/
it says "botclient.tk’s server IP address could not be found." 
btw I have the extension 

I also tried to host it on my own on a hosting site
but it is blank 
here is the site: https://discord-bot-client.typicalninja.repl.co

![image](https://user-images.githubusercontent.com/65993466/89488851-aa5dec80-d7c6-11ea-9f20-829b1f1cf3c4.png)

![image](https://user-images.githubusercontent.com/65993466/89488959-f90b8680-d7c6-11ea-8097-8a408972beb9.png)

thanks

**Comment by typicalninja493** [comment]
![image](https://user-images.githubusercontent.com/65993466/89489053-34a65080-d7c7-11ea-869d-7fda0dc1f157.png)

**Comment by typicalninja493** [comment]
after a few minutes my site i hosted shows this 
![image](https://user-images.githubusercontent.com/65993466/89489912-26f1ca80-d7c9-11ea-9691-3c5b6beebed1.png)

**Comment by mickokun** [comment]
the site is no more, only the app will work now if it doesnt break for you too like it did for me

**Comment by TheDealerOG** [comment]
> the site is no more, only the app will work now if it doesnt break for you too like it did for me

where did you get this info?

**Comment by RJain12** [comment]
The site got taken down, you can probably find more info in Flam3rboy's Discord server. Good luck!

**Comment by typicalninja493** [comment]
can you give me the link to his discord

**Comment by J3TL34RF0UR** [comment]
> the site is no more, only the app will work now if it doesnt break for you too like it did for me

What APP?!?!
