### ISSUE TITLE
Mac M1 Chip 2021 BigSur

### ISSUE THREAD

**Issue by MysteriouslyMythica** [Flam3rboy/discord-bot-client#251]
When opening the application on the mac, it seems like it instantly crashes!  Tried multiple times to open, no success.

**Comment by Kangaroo379** [comment]
Happened to me too I also opened an issue but so far it seems like they are still working on it

**Comment by Flam3rboy** [comment]
try the solution of #165

**Comment by MysteriouslyMythica** [comment]
> try the solution of #165

does not work strangely
