### ISSUE TITLE
Completely blank screen

### ISSUE THREAD

**Issue by Saturn123248** [Flam3rboy/discord-bot-client#252]
Hi i installed D.B.C (discord bot client) and i can't enter the page the page is blank i tried to reload using (crtl+r), reinstalling the app, restart the app and pc, using a portable version and nothing working plz help me :'( 

BTW im using windows 7/ 32 type processor
The version of D.B.C is 3.1.0

**Comment by Flam3rboy** [comment]
windows 7 is not supported
