### ISSUE TITLE
Join Other Severs (Bug)

### ISSUE THREAD

**Issue by HereIsFnfNessAndLucas** [Flam3rboy/discord-bot-client#257]
I Really Want To Join To Another Server BUT ITS ERROR IT SAID its invalid

**Comment by Flam3rboy** [comment]
You can’t you must be invited as a bot

**Comment by HereIsFnfNessAndLucas** [comment]
oh

**Comment by HereIsFnfNessAndLucas** [comment]
but in top.gg i want to try some gifs

**Comment by Flam3rboy** [comment]
then ask someone to invite your bot
