### ISSUE TITLE
Discord Bot Client Program is broken

### ISSUE THREAD

**Issue by MichaelGamng** [Flam3rboy/discord-bot-client#26]
When I first opened the program, it was basically loading(I think), but then it turned white and doesn't show anything.

![image](https://user-images.githubusercontent.com/62964686/89495887-eb073700-d7c1-11ea-9414-7c85d4d5ea90.png)

**Comment by gadielisawesome** [comment]
Check your internet connection.
Try refreshing the page.

View >> Refresh or Force Refresh

**Comment by MichaelGamng** [comment]
> Check your internet connection.
> Try refreshing the page.
> 
> View >> Refresh or Force Refresh

I tried that, but it still doesn't work. My internet connection is working good and it's fast.

**Comment by Flam3rboy** [comment]
Download the new Version 3.1.0 https://github.com/Flam3rboy/discord-bot-client/releases/latest
