### ISSUE TITLE
Can't login with TOKEn

### ISSUE THREAD

**Issue by ChickPeeB** [Flam3rboy/discord-bot-client#263]
When you give the token it again asks to sign in with a discord account.

![image](https://user-images.githubusercontent.com/74021010/119215151-86fff600-bae9-11eb-9575-8597ef9058ac.png)

![image](https://user-images.githubusercontent.com/74021010/119215160-90895e00-bae9-11eb-925e-336cf5653ff2.png)

**Comment by Flam3rboy** [comment]
You are using the wrong token, make sure not to copy the client secret and the bot token instead.
Also duplicate of #158
