### ISSUE TITLE
App and website not working

### ISSUE THREAD

**Issue by TomOS-F** [Flam3rboy/discord-bot-client#27]
Yesterday i tried using the website but whatever i tried i couldn't get it to work (and yes i have the extension), i tried the app, same, blank screen, and then, i tried hosting it myself on my own computer, however, that didn't seem to work either, i had a black screen, any idea why?

**Comment by DeltaCoderr** [comment]
Yes, It's down.

**Comment by ASFdirrt** [comment]
I didn't had a black screen, but i had a white one. I fixed it going to the "View" button and then clicking on "Reload" or "Force Reload"
