### ISSUE TITLE
I cant install

### ISSUE THREAD

**Issue by Fynnlukah** [Flam3rboy/discord-bot-client#272]
Cant install

**Comment by pedrokpp** [comment]
Please be more descriptive in your issues so we can help you install it

**Comment by Fynnlukah** [comment]
i said i cant Download

kp ***@***.***> schrieb am Fr., 2. Juli 2021, 17:55:

**Comment by Flam3rboy** [comment]
what did you try, what os are you using, can you send the link the file you were trying to download?

**Comment by pedrokpp** [comment]
Assuming you are using Windows, you should download and use [this](https://github.com/Flam3rboy/discord-bot-client/releases/download/3.1.0/Discord.Bot.Client.Setup.3.1.0.exe) to install it

**Comment by Flam3rboy** [comment]
Closed because of inactivity
