### ISSUE TITLE
Wont open correctly

### ISSUE THREAD

**Issue by FoxEGIT** [Flam3rboy/discord-bot-client#274]
When I open the client it opens a new windows and all i see is dark gray color and a darker gray line above and nothing is loading like the login section or something
![image](https://user-images.githubusercontent.com/86878527/124353567-935a9100-dc07-11eb-9604-34f066eebfe5.png)

**Comment by Ryyyyy09** [comment]
same

**Comment by pedrokpp** [comment]
Is it the first time you're opening?

**Comment by DodoGames7** [comment]
i think the bot client is outdated

**Comment by DodoGames7** [comment]
not sure tho the reason why im saying this is because lts no longer updated

**Comment by happierret** [comment]
same
![image](https://user-images.githubusercontent.com/85071336/130647723-62006a12-1a60-4a89-b0a8-bade149a322b.png)

**Comment by pedrokpp** [comment]
well, as the creator of this project said: 
```
No longer Maintained, only security flaws and critical errors
Development continued in fosscord
```
you should use fosscord or another bot client, this one probably won't have any fixes anytime soon

**Comment by Flam3rboy** [comment]
conversation continued in #288
