### ISSUE TITLE
Members do not load

### ISSUE THREAD

**Issue by SracccGames** [Flam3rboy/discord-bot-client#276]
members do not load so you cant see who is in discord.
![2021-07-06](https://user-images.githubusercontent.com/83980971/124694108-a17e0b00-deae-11eb-9a35-8b7935548e92.png)

**Comment by TrueVulpis** [comment]
Your bot application needs to have "Server Member Intents" turned on. You'll find it under the bot section, it's the 4th button down. 
![image](https://user-images.githubusercontent.com/81141083/124714986-c96c7d80-df45-11eb-9793-a148b159a6ae.png)

**Comment by LIGHT-RIDER** [comment]
O

**Comment by Flam3rboy** [comment]
duplicate of #144

**Comment by SracccGames** [comment]
i dont see the bot section

**Comment by SracccGames** [comment]
i turned on same thing.

**Comment by SracccGames** [comment]
> Your bot application needs to have "Server Member Intents" turned on. You'll find it under the bot section, it's the 4th button down.
> ![image](https://user-images.githubusercontent.com/81141083/124714986-c96c7d80-df45-11eb-9793-a148b159a6ae.png)

i did turn on

**Comment by SracccGames** [comment]
still #144 is happening when i turn on settings.

**Comment by Flam3rboy** [comment]
> still #144 is happening when i turn on settings.

yes because its a bug
