### ISSUE TITLE
DIscord Bot Client

### ISSUE THREAD

**Issue by 1bossyt1** [Flam3rboy/discord-bot-client#277]
The app when opening its just appears a whitescreen nothing else its not loading something pls help me discord name : BOSS YT#0001

**Comment by LIGHT-RIDER** [comment]
I am also trying but am also failed

**Comment by LIGHT-RIDER** [comment]
How can I help you

**Comment by Flam3rboy** [comment]
> Hi! It happened to me too, if you have this problem, go to the "View" option up in the screen, then select "Reload" or "Force Reload" this should fix it.
