### ISSUE TITLE
NEW WEBSITE FOR EVERYONE SAYING IT'S NOT WORKING 

### ISSUE THREAD

**Issue by TheDealerOG** [Flam3rboy/discord-bot-client#28]
https://snazzah.github.io/Lightcord/
Thank me later :)

**Comment by typicalninja493** [comment]
thanks it actually works
no ides if its safe

**Comment by DeltaCoderr** [comment]
It clearly says they aren't responsible for your token stealing. Don't trust these sites which give 0 information about if this is safe or not.

**Comment by RJain12** [comment]
Nah, lightcord is safe for sure. Snazzah is a reputed developer in the community, I've used his stuff in the past.

**Comment by Flam3rboy** [comment]
Nothing is loading after I logged in. @TheDealerOG 
So I'm gonna close this issue if there is no better alternative.
