### ISSUE TITLE
[Bug] Docker version not working.

### ISSUE THREAD

**Issue by AstroOrbis** [Flam3rboy/discord-bot-client#280]
Using the `docker run -p 8080:3000 -d flam3rboy/discord-bot-client` command works just fine- Except that when I load into my localhost:8080, it shows a grey screen. Every time I reload the page, it prints "undefined undefined" to the terminal in Docker.

**Comment by Flam3rboy** [comment]
Docker is not supported anymore, you need to use the application in releases

**Comment by Flam3rboy** [comment]
yes

**Comment by AstroOrbis** [comment]
There is still a DOCKERFILE in the code though
