### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by ElijahGives** [Flam3rboy/discord-bot-client#286]
Upon logging in with over 5 servers, no servers are loaded properly, and after waiting at least 5 seconds, I get disconnected.

**Comment by TheGamer456YT** [comment]
man, can't you read that it's discontinued?

**Comment by Rexogamer** [comment]
To be fair, critical bugs are still being fixed it seems:
![image](https://user-images.githubusercontent.com/42586271/130595319-168bcf7e-ff68-4d3e-b99e-62bcfc295612.png)
