### ISSUE TITLE
Just Blank

### ISSUE THREAD

**Issue by TWC2008** [Flam3rboy/discord-bot-client#30]
https://gyazo.com/e60d3e95de32ad49c24943790e7d6e9a

Thanks!
Please Advise.
Thomas!

**Comment by ASFdirrt** [comment]
> https://gyazo.com/e60d3e95de32ad49c24943790e7d6e9a
> 
> Thanks!
> Please Advise.
> Thomas!
Hi! It happened the same to me, if you have this problem, go to the "View" option up in the screen, then select "Reload" or "Force Reload" this should fix it.

**Comment by TWC2008** [comment]
> > https://gyazo.com/e60d3e95de32ad49c24943790e7d6e9a
> > Thanks!
> > Please Advise.
> > Thomas!
> 
> Hi! It happened to me too, if you have this problem, go to the "View" option up in the screen, then select "Reload" or "Force Reload" this should fix it.

Hi, I just did what you said but..... It did nothing. If you have another ideas I am open to them!

**Comment by Panther4242** [comment]
Ich habe das gleiche Problem...

**Comment by MoonBarc** [comment]
I just started downloading random files and it seems that the portable one works.
Here's a link: https://github.com/Flam3rboy/discord-bot-client/releases/download/3.1.0/Discord.Bot.Client.3.1.0.Portable.exe

**Comment by TWC2008** [comment]
> I just started downloading random files and it seems that the portable one works.
> Here's a link: https://github.com/Flam3rboy/discord-bot-client/releases/download/3.1.0/Discord.Bot.Client.3.1.0.Portable.exe
> 
> EDIT: seems to be pretty buggy for me though.

I am going to try that now thanks!!
