### ISSUE TITLE
MacOS version not launching

### ISSUE THREAD

**Issue by Mine215** [Flam3rboy/discord-bot-client#31]
The macOS version of this app does not launch all it does it attempt to start and then crash. This might have already been pointed out I just wanted to make sure it was. Also I think this should be prioritized over new features so that the app can get to more people.

**Comment by Flam3rboy** [comment]
I'm working on complete rewrite

**Comment by Flam3rboy** [comment]
its working if you start it in the terminal:
```
/Applications/Discord\ Bot\ Client.app/Contents/MacOS/Discord\ Bot\ Client
```
