### ISSUE TITLE
member list have bug

### ISSUE THREAD

**Issue by PiauTW** [Flam3rboy/discord-bot-client#37]
normal discord:
![image](https://user-images.githubusercontent.com/46679502/89730948-eb2f5d00-da75-11ea-8534-c2abb2ee7b39.png)

bot client:
![image](https://user-images.githubusercontent.com/46679502/89730956-f7b3b580-da75-11ea-8fc7-b64c31fdf72d.png)

**Comment by Flam3rboy** [comment]
duplicate of #8
