### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Charliemp4** [Flam3rboy/discord-bot-client#38]
It crashes a **lot**

**Comment by Flam3rboy** [comment]
not for me?
also keep in mind not to execute user only actions, that bots cannot use.
Can you provide more info, when it crashes and console logs?

**Comment by Charliemp4** [comment]
Sometimes it won't open at all, I have a Lenovo ThinkPad 11e with windows
10 and 128 gb storage. x64 system and I have used it but keeps crashing
