### ISSUE TITLE
Broken assets everywhere

### ISSUE THREAD

**Issue by mihabozic123** [Flam3rboy/discord-bot-client#4]
ok so this has probably been reported but here i am anyways
List of broken assets:
- Clyde pfp
- Emojis
Icons in general
![image](https://user-images.githubusercontent.com/57255683/83546199-995fd900-a500-11ea-8783-f33477928f00.png)

**Comment by Flam3rboy** [comment]
Will be fixed in the next release in ~ 2 days

**Comment by mihabozic123** [comment]
nice, thanks
also  pclondtherepo and hosted t myself
it is ok  your webste tho
