### ISSUE TITLE
Demo down

### ISSUE THREAD

**Issue by MaxMuster3333** [Flam3rboy/discord-bot-client#42]
The demo at https://botclient.tk is unavailable.... Maybe it was taken down by Freenom?

**Comment by Ssmidge** [comment]
It got taken down by discord

**Comment by cyleja1234** [comment]
I can't get a .tk website just dont work for me

**Comment by YEEETT** [comment]
the site that botclient.tk was iframing also is just blank

**Comment by Ssmidge** [comment]
@Flam3rboy You can close this its been responded to.
