### ISSUE TITLE
Can't see messages or members?

### ISSUE THREAD

**Issue by ItsProyal** [Flam3rboy/discord-bot-client#43]
I was using it, it was then working fine other than the members not loading but I saw that it was a normal issue and to just not bother. But then no messages load, it just says "Load more messages", nothing I send gets sent and nothing they send I recieve?

No clue if this is an issue, as I can see "6" issues and didn't see it in them.
Kind of annoying cause it removes the whole point of me doing this.

Heres what I did before it happend:

Changed my pfp: worked fine after changing it and others did the same and it worked.
Then I was kicked from a discord server: So I kicked my self from the discord server because it was an old discord server.
Then I joined a new one that I made recently and now I cant see anything, idk if the kicking broke it or what?

**Comment by NivaLada** [comment]
+1

**Comment by Flam3rboy** [comment]
its a known issue please logout and login again

**Comment by ItsProyal** [comment]
ok thanks it worked
