### ISSUE TITLE
Stealing accounts question.

### ISSUE THREAD

**Issue by GitHubSucks12** [Flam3rboy/discord-bot-client#44]
Hello! I don't know anything in programming, but still i want to ask, how i can be sure this programm doesn't log my password?

**Comment by Flam3rboy** [comment]
you shouldn't enter your password anywhere on the site.
If you see a login page with email + password just refresh with CTRL+R

**Comment by GitHubSucks12** [comment]
> you shouldn't enter your password anywhere on the site.
> If you see a login page with email + password just refresh with CTRL+R

Im not talking about this, im asking about if it's logs my password if i open it.

**Comment by Flam3rboy** [comment]
no, of course not, and if you don't believe me just look in the source code
