### ISSUE TITLE
doesnt open on mac

### ISSUE THREAD

**Issue by laestriol** [Flam3rboy/discord-bot-client#48]
i downloaded this twice, and i cant seem to open it on mac; everytime i open it, (dmg) it opens then closes. everytime when i use zip, it doesnt even open

**Comment by SiaALT** [comment]
> i downloaded this twice, and i cant seem to open it on mac; everytime i open it, (dmg) it opens then closes. everytime when i use zip, it doesnt even open

**Same here. I'm in the assistance server for discord and I'm trying to find out how to fix this. If I do, I will tell you.**

**Comment by Assfugil** [comment]
Mac is a bit buggy, you just need to go into the terminal application and type:
```
/Applications/Discord\ Bot\ Client.app/Contents/MacOS/Discord\ Bot\ Client
```
https://media.discordapp.net/attachments/742433506076000346/742484982144041030/unknown.png
