### ISSUE TITLE
Client for smartphone? 

### ISSUE THREAD

**Issue by KamileqZlola** [Flam3rboy/discord-bot-client#49]
Hi,

I wanted to ask if there are plans to create discord  client bot for andoid and ios?  

And how will it be for older phones too?  
Because I would like to add to my s4 mini.

Thanks for any reply.

😁

**Comment by SiaALT** [comment]
> Hi,
> 
> I wanted to ask if there are plans to create discord client bot for andoid and ios?
> 
> And how will it be for older phones too?
> Because I would like to add to my s4 mini.
> 
> Thanks for any reply.
> 
> 😁
### Not really sure..
**I dont think there is any way for discord client bot to suit mobile phones and tablets etc. So i don't think that even is possible. Sorry if this didn't help.** -Sia
