### ISSUE TITLE
discordclient.com not working and error when trying to npm start

### ISSUE THREAD

**Issue by burritosoftware** [Flam3rboy/discord-bot-client#5]

**Comment by Flam3rboy** [comment]
What is the error on discordclient.com and what error does get printed, if you do npm start?

**Comment by PBJF** [comment]
![image](https://user-images.githubusercontent.com/42769969/84147056-6d46d980-aa65-11ea-84a9-5f34ef585a32.png)

**Comment by Flam3rboy** [comment]
It should now be resolved, reopen the issue if you have questions
