### ISSUE TITLE
MAKE A MOBILE VERSION

### ISSUE THREAD

**Issue by SultanGG129** [Flam3rboy/discord-bot-client#50]
PLS MAKE A MOBILE VERSION PLEAAASE

### PLEAAAASE

**Comment by xNaCly** [comment]
Is in work currently, if you want to speed the process up, think about donating to Flam3rboys [Patreon](https://www.patreon.com/flam3rboy)

**Comment by ErzaScarletFairyTail** [comment]
Hello, how long will it take you to create the mobile version? and is it possible to have the connection source code discord with a token? Please.
Thanks.

**Comment by xNaCly** [comment]
it is in work.

**Comment by pikabelzy** [comment]
how long will it take?

**Comment by xNaCly** [comment]
idk
