### ISSUE TITLE
USE  BRANCHES

### ISSUE THREAD

**Issue by cyleja1234** [Flam3rboy/discord-bot-client#55]
you made an error in your code and messed the whole shit up!
I used git to download it and got a few errors showed up.

**Comment by mouncg** [comment]
please use branches, it makes code cleaner and allows multiple developers to work on their own features at the same time. this is what git is for.

**Comment by KeafyIsHere** [comment]
whats the error?

**Comment by Flam3rboy** [comment]
The whole code is in index.html
The Electron ab just loads it.
If you want to contribute fork the repo and make a pull request
