### ISSUE TITLE
Can't claim account.

### ISSUE THREAD

**Issue by keatonbuilder** [Flam3rboy/discord-bot-client#61]
I can't claim the account.
![image](https://user-images.githubusercontent.com/69707286/90305662-5fa93800-de8a-11ea-884e-4a8266d56b94.png)

**Comment by Ssmidge** [comment]
You can't claim bots?

**Comment by haydenwalker980** [comment]
You have to restart the app.

**Comment by keatonbuilder** [comment]
> You have to restart the app.

i tried doent work

**Comment by Flam3rboy** [comment]
logout and login again
