### ISSUE TITLE
Doesn't open on Mac

### ISSUE THREAD

**Issue by Dhruvvvv5** [Flam3rboy/discord-bot-client#62]
After giving all the permissions, It doesn't even open and throws an error that it quit unexpectedly

**Comment by KeafyIsHere** [comment]
Hi @Dhruvvvv5, are you using installer or source?

**Comment by Dhruvvvv5** [comment]
Hello,

I tried installing from both places but none of them worked..
Even after giving all perms it shows that the application quit
unexpectedly..

**Comment by Dhruvvvv5** [comment]
But Yes i tried it again it works!..Thank you so much!
