### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Nathanified** [Flam3rboy/discord-bot-client#64]
i open the .exe and all i see is a white screen, if i try to reload/force reload it turns to the discord background color for about 2 seconds then goes back to white

**Comment by Ssmidge** [comment]
Restart it if not try to use a portable version.

**Comment by KeafyIsHere** [comment]
Hi @Nathanified, Does anything show up in console tab in devtools?

**Comment by mozartrafi** [comment]
Yeah me too

**Comment by fe4rless-oss** [comment]
Have you guys found a solution yet? Im still having this problem if you would respond fast that would be nice :(

**Comment by fe4rless-oss** [comment]
this is what it shows in devtools https://ibb.co/16C3WC3 hope you guys fix this soon

**Comment by fe4rless-oss** [comment]
it doesnt show anything in console

**Comment by xNaCly** [comment]
Read the [FAQ](https://github.com/Flam3rboy/discord-bot-client/blob/master/FAQ.md).
