### ISSUE TITLE
client stuck at connecting

### ISSUE THREAD

**Issue by jerl0** [Flam3rboy/discord-bot-client#7]
![image](https://user-images.githubusercontent.com/5354621/84543742-c48cba00-acb0-11ea-9de0-cb00b405f0cd.png)

**Comment by Flam3rboy** [comment]
So the problem is that you are using http and not https and discord is trying to connect the the unsecure http discord servers.
I'm gonne fix this

**Comment by Flam3rboy** [comment]
Fixed this now in the newest commit
