### ISSUE TITLE
won't open on mac

### ISSUE THREAD

**Issue by XxERRORCODExX** [Flam3rboy/discord-bot-client#73]
its says discord bot client crashed unexpectedly.

**Comment by Alpinz** [comment]
same here

**Comment by asdf80000** [comment]
same here

**Comment by xNaCly** [comment]
yes, so? use a vm

**Comment by rayfruit** [comment]
this is ridiculous, why should people use VMs for an app that's technically available for Mac?

**Comment by Axo-The-Lord** [comment]
I agree. We shouldn't have to use a VM since the application should be available for Mac. I can't use a VM anyway.

**Comment by Flam3rboy** [comment]
duplicate of #165
