### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by LukehTM** [Flam3rboy/discord-bot-client#79]
When I try to log in as a bot I get the login screen for 1 second and then I get asked to log in with a normal account, any solutions?

**Comment by U-siro** [comment]
+1, same issue

**Comment by Flam3rboy** [comment]
thats a new issue, did you copy the right bot token?
If you copied the wrong token, entered it in the input field, clicked on login, but got a login screen with a email/password your token is invalid.

**Comment by Disrooting** [comment]
Just tried it myself now, it got stuck in a white screen for a minute, then i decided to reload the screen and i got inside the bot after. Great work, hopefully this will keep being maintained
