### ISSUE TITLE
member list scrambled

### ISSUE THREAD

**Issue by mihabozic123** [Flam3rboy/discord-bot-client#8]
![image](https://user-images.githubusercontent.com/57255683/84575573-53333100-adae-11ea-87a8-12d401a5b392.png)

**Comment by PBJF** [comment]
this is free product shut up and stop complaining

**Comment by Flam3rboy** [comment]
yes I know Discord have a different member API for bots than for users

**Comment by ivanghi1995** [comment]
> 
> 
> this is free product shut up and stop complaining

You're right, the project should not evolve in any way. We, the users should not report any bug so the developer doesn't feel bad and have to find them by himself (sarcasm)
