### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by matttMP** [Flam3rboy/discord-bot-client#88]
![image](https://user-images.githubusercontent.com/66797927/91379326-0c1ede80-e7e8-11ea-8c75-ad7da6ea1ef7.png)

**Comment by qxlights** [comment]
Happened to me aswell, I recommend **[building](https://github.com/Flam3rboy/discord-bot-client#build)** it rather than downloading it. Use [iTerm](https://www.iterm2.com/) or your regular Macintosh terminal to build the client.

**Comment by matttMP** [comment]
That got it to open. Although, how do I start it after I close it again? Sorry for the stupid question

**Comment by milanmdev** [comment]
Having the same error. Lemme try building it

**Comment by milanmdev** [comment]
Worked!
