### ISSUE TITLE
How to uninstall ?? Pls help

### ISSUE THREAD

**Issue by Prakul2006** [Flam3rboy/discord-bot-client#89]
I installed the client by downloading nodejs using build instructions[https://github.com/Flam3rboy/discord-bot-client#build](url) pls guide me how to uninstall

**Comment by jasger** [comment]
If you you use winwows you press the winows key, then you go to D under your program list. Now you need to find Discord Bot Client if you found it, make a right click on it and the press uninstall. Now there should open up a new window there you can either look for Discord Bot Client or search it, as soon as you found it just make a right click press uninstall and then confirm it in the window that should appear. (If there are any spelling mistakes I'm sorry I'm not from England)

**Comment by Flam3rboy** [comment]
if you installed nodejs, please follow the [uninstallation guide](https://www.google.com/search?q=nodejs+uninstall ) from nodejs
