### ISSUE TITLE
Crashes in Mac

### ISSUE THREAD

**Issue by mcatta123** [Flam3rboy/discord-bot-client#93]
installed the program in dmg and zip version and it crashes

**Comment by kezvon** [comment]
Yeah, it doesn't work on Mac. Wait though, developers are fixing the Mac version.

**Comment by Assfugil** [comment]
you need to launch it from the terminal

**Comment by mcatta123** [comment]
how do i launch it from the terminal?

**Comment by dhkim0800** [comment]
#81 Check this. There's the answer.
