### ISSUE TITLE
shown to  standard discord login after entering bot token

### ISSUE THREAD

**Issue by throweee** [Flam3rboy/discord-bot-client#98]
start program, enter bot token. after entering the bot token the only thing that appears is the standard discord login.

**Comment by Felp657** [comment]
Force reload then it switches back to enter bot token

**Comment by throweee** [comment]
correct, and entering the token again brings me to the standard login again,

**Comment by Assfugil** [comment]
then your token is wrong

**Comment by helloHELLO423** [comment]
same here, the token is not wrong, and I always refresh the token logger comes back but when I paste it back in, it takes me to normal discord
