### ISSUE TITLE
can't friend users

### ISSUE THREAD

**Issue by pikuaSHK** [Flam3rboy/discord-bot-client#99]
When i'm on my bot account, I can't friend any discord users.

**Comment by pikuaSHK** [comment]
If adding friends in the client is supposed to work, then idk why it isn't working for me.  If it isn't added/isn't supposed to work, then can you make a version that can? (i'm trying to make the bot my main account)

**Comment by CE1CECL** [comment]
Not supported by discord api

**Comment by minhducsun2002** [comment]
bot can't make friends

**Comment by Mariogamerexpert** [comment]
Unfortunately, Discord bots naturally cannot make friends, on the regular software nor the client.
